import java.util.ArrayList;
import java.util.List;
import java.util.Collections;

public class BruteForce {

    public static List<Integer> toInteger(Object[] cardValue){
        List<Integer> newCard = new ArrayList<>(4);
        for (int i = 0; i < cardValue.length; i++) {
            newCard.add(i, (Integer) cardValue[i]);
        }
        return newCard;
    }

    public static void permutasi(List<List<Integer>> allPermutation, List<Integer> cardValue, int j){
        for (int i = j; i < cardValue.size(); i++) {
            Collections.swap(cardValue, i, j);
            permutasi(allPermutation, cardValue, j+1);
            Collections.swap(cardValue, j, i);
        }
        if (j == cardValue.size()-1){
            allPermutation.add(toInteger(cardValue.toArray()));
        }
    }

    public static List<List<Integer>> removeIntDuplicates(List<List<Integer>> list){  
        // Create a new ArrayList
        List<List<Integer>> newList = new ArrayList<List<Integer>>();
  
        // Traverse through the first list
        for (int i = 0; i < list.size(); i++) {
            if (!newList.contains(list.get(i))) {
                newList.add(list.get(i));
            }   
        }
  
        // return the new list
        return newList;
    }

    public static List<List<String>> removeStringDuplicates(List<List<String>> list){  
        // Create a new ArrayList
        List<List<String>> newList = new ArrayList<List<String>>();
  
        // Traverse through the first list
        for (int i = 0; i < list.size(); i++) {
            if (!newList.contains(list.get(i))) {
                newList.add(list.get(i));
            }   
        }
  
        // return the new list
        return newList;
    }

    public static void printHasilPlusMin(List<String> result, List<Integer>cardValue, String OPBRACKET1, String OPBRACKET2, String OPBRACKET3, int a, int b, int c, int d){
        result.add("(("+a+OPBRACKET1+b+")"+OPBRACKET2+c+")"+OPBRACKET3+d);
        result.add("("+a+OPBRACKET1+"("+b+OPBRACKET2+c+"))"+OPBRACKET3+d);
        result.add("("+a+OPBRACKET1+b+")"+OPBRACKET2+"("+c+OPBRACKET3+d+")");
        result.add(a+OPBRACKET1+"(("+b+OPBRACKET2+c+")"+OPBRACKET3+d+")");
    }
    
    public static List<String> getAllResult(List<Integer> cardValue) {
        //Kamus
        String[] opp={"+","-","*","/"};
        List<String> allResult  = new ArrayList<>();
        List<List<Integer>> allPermutation = new ArrayList<List<Integer>>();
        
        //Algoritma
        permutasi(allPermutation, cardValue, 0);
        allPermutation=removeIntDuplicates(allPermutation);
            
        for (int i = 0; i < allPermutation.size(); i++) {
            int a=allPermutation.get(i).get(0);
            int b=allPermutation.get(i).get(1);
            int c=allPermutation.get(i).get(2);
            int d=allPermutation.get(i).get(3);
            //
            if(a+b+c+d==24){
                printHasilPlusMin(allResult, cardValue, opp[0], opp[0], opp[0], a, b, c, d);
            }
            if(a+b+c-d==24){
                printHasilPlusMin(allResult, cardValue, opp[0], opp[0], opp[1], a, b, c, d);
            }
            if(a+b-c+d==24){
                printHasilPlusMin(allResult, cardValue, opp[0], opp[1], opp[0], a, b, c, d);
            }
            if(a-b+c+d==24){
                printHasilPlusMin(allResult, cardValue, opp[1], opp[0], opp[0], a, b, c, d);
            }
            if(a+b-c-d==24){
                printHasilPlusMin(allResult, cardValue, opp[0], opp[1], opp[1], a, b, c, d);
            }
            if(a-b+c-d==24){
                printHasilPlusMin(allResult, cardValue, opp[1], opp[0], opp[1], a, b, c, d);
            }
            if(a-b-c+d==24){
                printHasilPlusMin(allResult, cardValue, opp[1], opp[1], opp[0], a, b, c, d);
            }
            if(((a*b)+c)+d==24){
                allResult.add("(("+a+"*"+b+")+"+c+")+"+d);
            }
            if((a*(b+c))+d==24){
                allResult.add("("+a+"*("+b+"))+"+c+"+"+d+"");
            }
            if((a*b)+(c+d)==24){
                allResult.add("(("+a+"*"+b+")+("+c+"+"+d+")");
            }
            if(a*(b+(c+d))==24){
                allResult.add(""+a+"*("+b+"+("+c+"+"+d+"))");
            }
            if(((a+b)+c)*d==24){
                allResult.add("(("+a+"+"+b+")+"+c+")*"+d);
            }
            if((a+(b+c))*d==24){
                allResult.add("("+a+"+("+b+"))+"+c+"*"+d+"");
            }
            if((a+b)+(c*d)==24){
                allResult.add("(("+a+"+"+b+")+("+c+"*"+d+")");
            }
            if(a+(b+(c*d))==24){
                allResult.add(""+a+"+("+b+"+("+c+"*"+d+"))");
            }
            if(((a+b)+c)/d==24){
                allResult.add("(("+a+"+"+b+")+"+c+")/"+d);
            }
            if((a+(b+c))/d==24){
                allResult.add("("+a+"+("+b+"))+"+c+"/"+d+"");
            }
            if((a+b)+(c/d)==24){
                allResult.add("(("+a+"+"+b+")+("+c+"/"+d+")");
            }
            if(a+(b+(c/d))==24){
                allResult.add(""+a+"+"+b+"+("+c+"(/"+d+"))");
            }
            if(((a+b)-c)*d==24){
                allResult.add("(("+a+"+"+b+")-"+c+")*"+d);
            }
            if((a+(b-c))*d==24){
                allResult.add("("+a+"+("+b+"))-"+c+"*"+d+"");
            }
            if((a+b)-(c*d)==24){
                allResult.add("(("+a+"+"+b+")-("+c+"*"+d+")");
            }
            if(a+(b-(c*d))==24){
                allResult.add(""+a+"+("+b+"-("+c+"*"+d+"))");
            }
            if(((a+b)-c)/d==24){
                allResult.add("(("+a+"+"+b+")-"+c+")/"+d);
            }
            if((a+(b-c))/d==24){
                allResult.add("("+a+"+("+b+"))-"+c+"/"+d+"");
            }
            if((a+b)-(c/d)==24){
                allResult.add("(("+a+"+"+b+")-("+c+"/"+d+")");
            }
            if(a+(b-(c/d))==24){
                allResult.add(""+a+"+("+b+"-("+c+"/"+d+"))");
            }
            if(((a+b)*c)+d==24){
                allResult.add("(("+a+"+"+b+")*"+c+")+"+d);
            }
            if((a+(b*c))+d==24){
                allResult.add("("+a+"+("+b+"))*"+c+"+"+d+"");
            }
            if((a+b)*(c+d)==24){
                allResult.add("(("+a+"+"+b+")*("+c+"+"+d+")");
            }
            if(a+(b*(c+d))==24){
                allResult.add(""+a+"+("+b+"*("+c+"+"+d+"))");
            }
            if(((a+b)*c)-d==24){
                allResult.add("(("+a+"+"+b+")*"+c+")-"+d);
            }
            if((a+(b*c))-d==24){
                allResult.add("("+a+"+("+b+"))*"+c+"-"+d+"");
            }
            if((a+b)*(c-d)==24){
                allResult.add("(("+a+"+"+b+")*("+c+"-"+d+")");
            }
            if(a+(b*(c-d))==24){
                allResult.add(""+a+"+("+b+"*("+c+"-"+d+"))");
            }
            if(((a+b)*c)*d==24){
                allResult.add("(("+a+"+"+b+")*"+c+")*"+d);
            }
            if((a+(b*c))*d==24){
                allResult.add("("+a+"+("+b+"))*"+c+"*"+d+"");
            }
            if((a+b)*(c*d)==24){
                allResult.add("(("+a+"+"+b+")*("+c+"*"+d+")");
            }
            if(a+(b*(c*d))==24){
                allResult.add(""+a+"+("+b+"*("+c+"*"+d+"))");
            }
            if(((a+b)*c)/d==24){
                allResult.add("(("+a+"+"+b+")*"+c+")/"+d);
            }
            if((a+(b*c))/d==24){
                allResult.add("("+a+"+("+b+"))*"+c+"/"+d+"");
            }
            if((a+b)*(c/d)==24){
                allResult.add("(("+a+"+"+b+")*("+c+"/"+d+")");
            }
            if(a+(b*(c/d))==24){
                allResult.add(""+a+"+("+b+"*("+c+"/"+d+"))");
            }
            if(((a+b)/c)+d==24){
                allResult.add("(("+a+"+"+b+")/"+c+")+"+d);
            }
            if((a+(b/c))+d==24){
                allResult.add("("+a+"+("+b+"))/"+c+"+"+d+"");
            }
            if((a+b)/(c+d)==24){
                allResult.add("(("+a+"+"+b+")/("+c+"+"+d+")");
            }
            if(a+(b/(c+d))==24){
                allResult.add(""+a+"+("+b+"/("+c+"+"+d+"))");
            }
            if(((a+b)/c)-d==24){
                allResult.add("(("+a+"+"+b+")/"+c+")-"+d);
            }
            if((a+(b/c))-d==24){
                allResult.add("("+a+"+("+b+"))/"+c+"-"+d+"");
            }
            if(c-d!=0){
                if((a+b)/(c-d)==24){
                    allResult.add("(("+a+"+"+b+")/("+c+"-"+d+")");
                }
                if(a+(b/(c-d))==24){
                    allResult.add(""+a+"+("+b+"/("+c+"-"+d+"))");
                }
            }
            if(((a+b)/c)*d==24){
                allResult.add("(("+a+"+"+b+")/"+c+")*"+d);
            }
            if((a+(b/c))*d==24){
                allResult.add("("+a+"+("+b+"))/"+c+"*"+d+"");
            }
            if((a+b)/(c*d)==24){
                allResult.add("(("+a+"+"+b+")/("+c+"*"+d+")");
            }
            if(a+(b/(c*d))==24){
                allResult.add(""+a+"+("+b+"/("+c+"*"+d+"))");
            }
            if(((a+b)/c)/d==24){
                allResult.add("(("+a+"+"+b+")/"+c+")/"+d);
            }
            if((a+(b/c))/d==24){
                allResult.add("("+a+"+("+b+"))/"+c+"/"+d+"");
            }
            if(c>=d&&a+b>=(c/d)){
                if((a+b)/(c/d)==24){
                    allResult.add("(("+a+"+"+b+")/("+c+"/"+d+")");
                }
            }
            if(c>=d&&b>c/d){
                if(a+(b/(c/d))==24){
                    allResult.add(""+a+"+("+b+"/("+c+"/"+d+"))");
                }
            }
            if(((a+b)-c)*d==24){
                allResult.add("(("+a+"+"+b+")-"+c+")*"+d);
            }
            if((a+(b-c))*d==24){
                allResult.add("("+a+"+("+b+"))-"+c+"*"+d+"");
            }
            if((a+b)-(c*d)==24){
                allResult.add("(("+a+"+"+b+")-("+c+"*"+d+")");
            }
            if(a+(b-(c*d))==24){
                allResult.add(""+a+"+("+b+"-("+c+"*"+d+"))");
            }
            if(((a+b)-c)/d==24){
                allResult.add("(("+a+"+"+b+")-"+c+")/"+d);
            }
            if((a+(b-c))/d==24){
                allResult.add("("+a+"+("+b+"))-"+c+"/"+d+"");
            }
            if((a+b)-(c/d)==24){
                allResult.add("(("+a+"+"+b+")-("+c+"/"+d+")");
            }
            if(a+(b-(c/d))==24){
                allResult.add(""+a+"+("+b+"-("+c+"/"+d+"))");
            }
            if(((a-b)-c)*d==24){
                allResult.add("(("+a+"-"+b+")-"+c+")*"+d);
            }
            if((a-(b-c))*d==24){
                allResult.add("("+a+"-("+b+"))-"+c+"*"+d+"");
            }
            if((a-b)-(c*d)==24){
                allResult.add("(("+a+"-"+b+")-("+c+"*"+d+")");
            }
            if(a-(b-(c*d))==24){
                allResult.add(""+a+"-("+b+"-("+c+"*"+d+"))");
            }
            if(((a-b)*c)+d==24){
                allResult.add("(("+a+"-"+b+")*"+c+")+"+d);
            }
            if((a-(b*c))+d==24){
                allResult.add("("+a+"-("+b+"))*"+c+"+"+d+"");
            }
            if((a-b)*(c+d)==24){
                allResult.add("(("+a+"-"+b+")*("+c+"+"+d+")");
            }
            if(a-(b*(c+d))==24){
                allResult.add(""+a+"-("+b+"*("+c+"+"+d+"))");
            }
            if(((a-b)*c)+d==24){
                allResult.add("(("+a+"-"+b+")*"+c+")+"+d);
            }
            if((a-(b*c))+d==24){
                allResult.add("("+a+"-("+b+"))*"+c+"+"+d+"");
            }
            if((a-b)*(c+d)==24){
                allResult.add("(("+a+"-"+b+")*("+c+"+"+d+")");
            }
            if(a-(b*(c+d))==24){
                allResult.add(""+a+"-("+b+"*("+c+"+"+d+"))");
            }
            if(((a-b)*c)-d==24){
                allResult.add("(("+a+"-"+b+")*"+c+")-"+d);
            }
            if((a-(b*c))-d==24){
                allResult.add("("+a+"-("+b+"))*"+c+"-"+d+"");
            }
            if((a-b)*(c-d)==24){
                allResult.add("(("+a+"-"+b+")*("+c+"-"+d+")");
            }
            if(a-(b*(c-d))==24){
                allResult.add(""+a+"-("+b+"*("+c+"-"+d+"))");
            }
            if(((a-b)*c)*d==24){
                allResult.add("(("+a+"-"+b+")*"+c+")*"+d);
            }
            if((a-(b*c))*d==24){
                allResult.add("("+a+"-("+b+"))*"+c+"*"+d+"");
            }
            if((a-b)*(c*d)==24){
                allResult.add("(("+a+"-"+b+")*("+c+"*"+d+")");
            }
            if(a-(b*(c*d))==24){
                allResult.add(""+a+"-("+b+"*("+c+"*"+d+"))");
            }
            if(((a-b)*c)/d==24){
                allResult.add("(("+a+"-"+b+")*"+c+")/"+d);
            }
            if((a-(b*c))/d==24){
                allResult.add("("+a+"-("+b+"))*"+c+"/"+d+"");
            }
            if((a-b)*(c/d)==24){
                allResult.add("(("+a+"-"+b+")*("+c+"/"+d+")");
            }
            if(a-(b*(c/d))==24){
                allResult.add(""+a+"-("+b+"*("+c+"/"+d+"))");
            }
            if(((a-b)/c)+d==24){
                allResult.add("(("+a+"-"+b+")/"+c+")+"+d);
            }
            if((a-(b/c))+d==24){
                allResult.add("("+a+"-("+b+"))/"+c+"+"+d+"");
            }
            if((a-b)/(c+d)==24){
                allResult.add("(("+a+"-"+b+")/("+c+"+"+d+")");
            }
            if(a-(b/(c+d))==24){
                allResult.add(""+a+"-("+b+"/("+c+"+"+d+"))");
            }
            if(((a-b)/c)-d==24){
                allResult.add("(("+a+"-"+b+")/"+c+")-"+d);
            }
            if((a-(b/c))-d==24){
                allResult.add("("+a+"-("+b+"))/"+c+"-"+d+"");
            }
            if(c-d!=0){
                if((a-b)/(c-d)==24){
                    allResult.add("(("+a+"-"+b+")/("+c+"-"+d+")");
                }
                if(a-(b/(c-d))==24){
                    allResult.add(""+a+"-("+b+"/("+c+"-"+d+"))");
                }
            }
            if(((a-b)/c)*d==24){
                allResult.add("(("+a+"-"+b+")/"+c+")*"+d);
            }
            if((a-(b/c))*d==24){
                allResult.add("("+a+"-("+b+"))/"+c+"*"+d+"");
            }
            if((a-b)/(c*d)==24){
                allResult.add("(("+a+"-"+b+")/("+c+"*"+d+")");
            }
            if(a-(b/(c*d))==24){
                allResult.add(""+a+"-("+b+"/("+c+"*"+d+"))");
            }
            if(((a*b)+c)+d==24){
                allResult.add("(("+a+"*"+b+")+"+c+")+"+d);
            }
            if((a*(b+c))+d==24){
                allResult.add("("+a+"*("+b+"))+"+c+"+"+d+"");
            }
            if((a*b)+(c+d)==24){
                allResult.add("(("+a+"*"+b+")+("+c+"+"+d+")");
            }
            if(a*(b+(c+d))==24){
                allResult.add(""+a+"*("+b+"+("+c+"+"+d+"))");
            }
            if(((a*b)+c)-d==24){
                allResult.add("(("+a+"*"+b+")+"+c+")-"+d);
            }
            if((a*(b+c))-d==24){
                allResult.add("("+a+"*("+b+"))+"+c+"-"+d+"");
            }
            if((a*b)+(c-d)==24){
                allResult.add("(("+a+"*"+b+")+("+c+"-"+d+")");
            }
            if(a*(b+(c-d))==24){
                allResult.add(""+a+"*("+b+"+("+c+"-"+d+"))");
            }
            if(((a*b)+c)*d==24){
                allResult.add("(("+a+"*"+b+")+"+c+")*"+d);
            }
            if((a*(b+c))*d==24){
                allResult.add("("+a+"*("+b+"))+"+c+"*"+d+"");
            }
            if((a*b)+(c*d)==24){
                allResult.add("(("+a+"*"+b+")+("+c+"*"+d+")");
            }
            if(a*(b+(c*d))==24){
                allResult.add(""+a+"*("+b+"+("+c+"*"+d+"))");
            }
            if(((a*b)+c)/d==24){
                allResult.add("(("+a+"*"+b+")+"+c+")/"+d);
            }
            if((a*(b+c))/d==24){
                allResult.add("("+a+"*("+b+"))+"+c+"/"+d+"");
            }
            if((a*b)+(c/d)==24){
                allResult.add("(("+a+"*"+b+")+("+c+"/"+d+")");
            }
            if(a*(b+(c/d))==24){
                allResult.add(""+a+"*("+b+"+("+c+"/"+d+"))");
            }
            if(((a*b)-c)+d==24){
                allResult.add("(("+a+"*"+b+")-"+c+")+"+d);
            }
            if((a*(b-c))+d==24){
                allResult.add("("+a+"*("+b+"))-"+c+"+"+d+"");
            }
            if((a*b)-(c+d)==24){
                allResult.add("(("+a+"*"+b+")-("+c+"+"+d+")");
            }
            if(a*(b-(c+d))==24){
                allResult.add(""+a+"*("+b+"-("+c+"+"+d+"))");
            }
            if(((a*b)-c)-d==24){
                allResult.add("(("+a+"*"+b+")-"+c+")-"+d);
            }
            if((a*(b-c))-d==24){
                allResult.add("("+a+"*("+b+"))-"+c+"-"+d+"");
            }
            if((a*b)-(c-d)==24){
                allResult.add("(("+a+"*"+b+")-("+c+"-"+d+")");
            }
            if(a*(b-(c-d))==24){
                allResult.add(""+a+"*("+b+"-("+c+"-"+d+"))");
            }
            if(((a*b)-c)*d==24){
                allResult.add("(("+a+"*"+b+")-"+c+")*"+d);
            }
            if((a*(b-c))*d==24){
                allResult.add("("+a+"*("+b+"))-"+c+"*"+d+"");
            }
            if((a*b)-(c*d)==24){
                allResult.add("(("+a+"*"+b+")-("+c+"*"+d+")");
            }
            if(a*(b-(c*d))==24){
                allResult.add(""+a+"*("+b+"-("+c+"*"+d+"))");
            }
            if(((a*b)-c)/d==24){
                allResult.add("(("+a+"*"+b+")-"+c+")/"+d);
            }
            if((a*(b-c))/d==24){
                allResult.add("("+a+"*("+b+"))-"+c+"/"+d+"");
            }
            if((a*b)-(c/d)==24){
                allResult.add("(("+a+"*"+b+")-("+c+"/"+d+")");
            }
            if(a*(b-(c/d))==24){
                allResult.add(""+a+"*("+b+"-("+c+"/"+d+"))");
            }
            if(((a*b)*c)+d==24){
                allResult.add("(("+a+"*"+b+")*"+c+")+"+d);
            }
            if((a*(b*c))+d==24){
                allResult.add("("+a+"*("+b+"))*"+c+"+"+d+"");
            }
            if((a*b)*(c+d)==24){
                allResult.add("(("+a+"*"+b+")*("+c+"+"+d+")");
            }
            if(a*(b*(c+d))==24){
                allResult.add(""+a+"*("+b+"*("+c+"+"+d+"))");
            }
            if(((a*b)*c)-d==24){
                allResult.add("(("+a+"*"+b+")*"+c+")-"+d);
            }
            if((a*(b*c))-d==24){
                allResult.add("("+a+"*("+b+"))*"+c+"-"+d+"");
            }
            if((a*b)*(c-d)==24){
                allResult.add("(("+a+"*"+b+")*("+c+"-"+d+")");
            }
            if(a*(b*(c-d))==24){
                allResult.add(""+a+"*("+b+"*("+c+"-"+d+"))");
            }
            if(((a*b)*c)*d==24){
                allResult.add("(("+a+"*"+b+")*"+c+")*"+d);
            }
            if((a*(b*c))*d==24){
                allResult.add("("+a+"*("+b+"))*"+c+"*"+d+"");
            }
            if((a*b)*(c*d)==24){
                allResult.add("(("+a+"*"+b+")*("+c+"*"+d+")");
            }
            if(a*(b*(c*d))==24){
                allResult.add(""+a+"*("+b+"*("+c+"*"+d+"))");
            }
            if(((a*b)*c)/d==24){
                allResult.add("(("+a+"*"+b+")*"+c+")/"+d);
            }
            if((a*(b*c))/d==24){
                allResult.add("("+a+"*("+b+"))*"+c+"/"+d+"");
            }
            if((a*b)*(c/d)==24){
                allResult.add("(("+a+"*"+b+")*("+c+"/"+d+")");
            }
            if(a*(b*(c/d))==24){
                allResult.add(""+a+"*("+b+"*("+c+"/"+d+"))");
            }
            if(((a*b)/c)+d==24){
                allResult.add("(("+a+"*"+b+")/"+c+")+"+d);
            }
            if((a*(b/c))+d==24){
                allResult.add("("+a+"*("+b+"))/"+c+"+"+d+"");
            }
            if((a*b)/(c+d)==24){
                allResult.add("(("+a+"*"+b+")/("+c+"+"+d+")");
            }
            if(a*(b/(c+d))==24){
                allResult.add(""+a+"*("+b+"/("+c+"+"+d+"))");
            }
            if(((a*b)/c)-d==24){
                allResult.add("(("+a+"*"+b+")/"+c+")-"+d);
            }
            if((a*(b/c))-d==24){
                allResult.add("("+a+"*("+b+"))/"+c+"-"+d+"");
            }
            if(c-d!=0){
                if((a*b)/(c-d)==24){
                    allResult.add("(("+a+"*"+b+")/("+c+"-"+d+")");
                }
            
                if(a*(b/(c-d))==24){
                    allResult.add(""+a+"*("+b+"/("+c+"-"+d+"))");
                }
            }
            if(((a*b)/c)*d==24){
                allResult.add("(("+a+"*"+b+")/"+c+")*"+d);
            }
            if((a*(b/c))*d==24){
                allResult.add("("+a+"*("+b+"))/"+c+"*"+d+"");
            }
            if((a*b)/(c*d)==24){
                allResult.add("(("+a+"*"+b+")/("+c+"*"+d+")");
            }
            if(a*(b/(c*d))==24){
                allResult.add(""+a+"*("+b+"/("+c+"*"+d+"))");
            }
            if(((a*b)/c)/d==24){
                allResult.add("(("+a+"*"+b+")/"+c+")/"+d);
            }
            if((a*(b/c))/d==24){
                allResult.add("("+a+"*("+b+"))/"+c+"/"+d+"");
            }
            if(c>=d&&a*b>=c/d){
                if((a*b)/(c/d)==24){
                    allResult.add("(("+a+"*"+b+")/("+c+"/"+d+")");
                }
            }
            if(c>=d&&b>=c/d){
                if(a*(b/(c/d))==24){
                    allResult.add(""+a+"*("+b+"/("+c+"/"+d+"))");
                }
            }
            if(((a/b)/c)+d==24){
                allResult.add("(("+a+"/"+b+")/"+c+")+"+d);
            }
            if((b/c)>0){
                if((a/(b/c))+d==24){
                    allResult.add("("+a+"/("+b+"))/"+c+"+"+d+"");
                }
            }
            if((a/b)/(c+d)>0){
                if((a/b)/(c+d)==24){
                    allResult.add("(("+a+"/"+b+")/("+c+"+"+d+")");
                }
            }
            if(a>=b&&b>=c+d){
                if(a/(b/(c+d))==24){
                    allResult.add(""+a+"/("+b+"/("+c+"+"+d+"))");
                }
            }
            if(((a/b)+c)+d==24){
                allResult.add("(("+a+"/"+b+")+"+c+")+"+d);
            }
            if((a/(b+c))+d==24){
                allResult.add("("+a+"/("+b+"))+"+c+"+"+d+"");
            }
            if((a/b)+(c+d)==24){
                allResult.add("(("+a+"/"+b+")+("+c+"+"+d+")");
            }
            if(a/(b+(c+d))==24){
                allResult.add(""+a+"/("+b+"+("+c+"+"+d+"))");
            }
            if(((a/b)+c)-d==24){
                allResult.add("(("+a+"/"+b+")+"+c+")-"+d);
            }
            if((a/(b+c))-d==24){
                allResult.add("("+a+"/("+b+"))+"+c+"-"+d+"");
            }
            if((a/b)+(c-d)==24){
                allResult.add("(("+a+"/"+b+")+("+c+"-"+d+")");
            }
            if(a>=b+(c-d)&&b+(c-d)>0){
                if(a/(b+(c-d))==24){
                    allResult.add(""+a+"/("+b+"+("+c+"-"+d+"))");
                }
            }
            if(((a/b)+c)*d==24){
                allResult.add("(("+a+"/"+b+")+"+c+")*"+d);
            }
            if((a/(b+c))*d==24){
                allResult.add("("+a+"/("+b+"))+"+c+"*"+d+"");
            }
            if((a/b)+(c*d)==24){
                allResult.add("(("+a+"/"+b+")+("+c+"*"+d+")");
            }
            if(a/(b+(c*d))==24){
                allResult.add(""+a+"/("+b+"+("+c+"*"+d+"))");
            }
            if(((a/b)+c)/d==24){
                allResult.add("(("+a+"/"+b+")+"+c+")/"+d);
            }
            if((a/(b+c))/d==24){
                allResult.add("("+a+"/("+b+"))+"+c+"/"+d+"");
            }
            if((a/b)+(c/d)==24){
                allResult.add("(("+a+"/"+b+")+("+c+"/"+d+")");
            }
            if(a/(b+(c/d))==24){
                allResult.add(""+a+"/("+b+"+("+c+"/"+d+"))");
            }
            if(((a/b)-c)+d==24){
                allResult.add("(("+a+"/"+b+")-"+c+")+"+d);
            }
            if(b-c!=0){
                if((a/(b-c))+d==24){
                    allResult.add("("+a+"/("+b+"))-"+c+"+"+d+"");
                }
            }
            if((a/b)-(c+d)==24){
                allResult.add("(("+a+"/"+b+")-("+c+"+"+d+")");
            }
            if(b-(c+d)!=0){
                if(a/(b-(c+d))==24){
                    allResult.add(""+a+"/("+b+"-("+c+"+"+d+"))");
                }
            }
            if(((a/b)-c)*d==24){
                allResult.add("(("+a+"/"+b+")-"+c+")*"+d);
            }
            if(b-c!=0){
                if((a/(b-c))*d==24){
                    allResult.add("("+a+"/("+b+"))-"+c+"*"+d+"");
                }
            }
            if((a/b)-(c*d)==24){
                allResult.add("(("+a+"/"+b+")-("+c+"*"+d+")");
            }
            if(b-(c*d)!=0){
                if(a/(b-(c*d))==24){
                    allResult.add(""+a+"/("+b+"-("+c+"*"+d+"))");
                }
            }
            if(((a/b)*c)+d==24){
                allResult.add("(("+a+"/"+b+")*"+c+")+"+d);
            }
            if((a/(b*c))+d==24){
                allResult.add("("+a+"/("+b+"))*"+c+"+"+d+"");
            }
            if((a/b)*(c+d)==24){
                allResult.add("(("+a+"/"+b+")*("+c+"+"+d+")");
            }
            if(a/(b*(c+d))==24){
                allResult.add(""+a+"/("+b+"*("+c+"+"+d+"))");
            }
            if(((a/b)*c)-d==24){
                allResult.add("(("+a+"/"+b+")*"+c+")-"+d);
            }
            if((a/(b*c))-d==24){
                allResult.add("("+a+"/("+b+"))*"+c+"-"+d+"");
            }
            if(c-d!=0){
                if((a/b)*(c-d)==24){
                    allResult.add("(("+a+"/"+b+")*("+c+"-"+d+")");
                }
                if(a/(b*(c-d))==24){
                    allResult.add(""+a+"/("+b+"*("+c+"-"+d+"))");
                }
            }
            if(((a/b)*c)*d==24){
                allResult.add("(("+a+"/"+b+")*"+c+")*"+d);
            }
            if((a/(b*c))*d==24){
                allResult.add("("+a+"/("+b+"))*"+c+"*"+d+"");
            }
            if((a/b)*(c*d)==24){
                allResult.add("(("+a+"/"+b+")*("+c+"*"+d+")");
            }
            if(a/(b*(c*d))==24){
                allResult.add(""+a+"/("+b+"*("+c+"*"+d+"))");
            }
            if(((a/b)*c)/d==24){
                allResult.add("(("+a+"/"+b+")*"+c+")/"+d);
            }
            if((a/(b*c))/d==24){
                allResult.add("("+a+"/("+b+"))*"+c+"/"+d+"");
            }
            if((a/b)*(c/d)==24){
                allResult.add("(("+a+"/"+b+")*("+c+"/"+d+")");
            }
            if(c>d&&a>b*(c/d)){
                if(a/(b*(c/d))==24){
                    allResult.add(""+a+"/("+b+"*("+c+"/"+d+"))");
                }
            }
            if(((a/b)/c)*d==24){
                allResult.add("(("+a+"/"+b+")/"+c+")*"+d);
            }
            if(a>b&&b>c){
                if((a/(b/c))*d==24){
                    allResult.add("("+a+"/("+b+"))/"+c+"*"+d+"");
                }
            }
            if(a>b&&(a/b>c*d)){
                if((a/b)/(c*d)==24){
                    allResult.add("(("+a+"/"+b+")/("+c+"*"+d+")");
                }
            }
            if(a>b&&b>c*d){
                if(a/(b/(c*d))==24){
                    allResult.add(""+a+"/("+b+"/("+c+"*"+d+"))");
                }
            }
        }
        return allResult;
    }
}
